version: '3.1'
services:
  web:
    container_name: php_apache_pdo
    build: .
    volumes:
      # Volumnes para el control del sitio
      # El proyecto que trabajes debe estar en un servidor en la ruta /var/www/html/sitio
     - $PWD/www:/var/www/html
      #  Agregamos volumen del site-available
     - $PWD/conf:/etc/apache2/sites-available
    ports:
         - "9002:80" # Puerto para sitio estatico
